# -*- coding: utf-8 -*-
"""final lstm training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kl-0RD5RRq0Vsz-LkKWd3ni-1KajgjAe
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout


DATA_PATH = "/content/V008_features_final.csv"
df = pd.read_csv(DATA_PATH)

print("Dataset shape:", df.shape)
print("Columns:", df.columns.tolist())


print("\nMissing values:\n", df.isnull().sum())
print("\nShot distribution:\n", df["shot_type"].value_counts())


le = LabelEncoder()
df["label"] = le.fit_transform(df["shot_type"])

print("\nLabel mapping:")
for c, i in zip(le.classes_, le.transform(le.classes_)):
    print(c, "→", i)


feature_cols = [
    "wrist_vel","elbow_vel","ball_vel",
    "wrist_acc","ball_acc",
    "wrist_dx","wrist_dy","ball_dx","ball_dy",
    "arm_angle","arm_length",
    "wrist_ball_dist","elbow_ball_dist",
    "rel_speed","is_contact"
]


SEQ_LEN = 20

X = []
y = []

for pid in df["player_id"].unique():

    sub = df[df["player_id"] == pid]

    for i in range(len(sub) - SEQ_LEN):
        seq = sub.iloc[i:i+SEQ_LEN][feature_cols].values
        label = sub.iloc[i+SEQ_LEN]["label"]

        X.append(seq)
        y.append(label)

X = np.array(X)
y = np.array(y)

print("\nSequence shape:", X.shape)
print("Labels shape:", y.shape)


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("\nTrain shape:", X_train.shape)
print("Test shape:", X_test.shape)


model = Sequential([
    LSTM(64, return_sequences=True, input_shape=(SEQ_LEN, len(feature_cols))),
    Dropout(0.3),
    LSTM(32),
    Dropout(0.3),
    Dense(32, activation="relu"),
    Dense(len(le.classes_), activation="softmax")
])

model.compile(
    loss="sparse_categorical_crossentropy",
    optimizer="adam",
    metrics=["accuracy"]
)

model.summary()


history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=15,
    batch_size=64
)


loss, acc = model.evaluate(X_test, y_test)
print("\n🎯 Test Accuracy:", acc)


y_pred = model.predict(X_test)
y_pred = np.argmax(y_pred, axis=1)

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt="d", xticklabels=le.classes_, yticklabels=le.classes_)
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Confusion Matrix")
plt.show()


print("\nClassification Report:\n")
print(classification_report(y_test, y_pred, target_names=le.classes_))


model.save("/content/tennis_shot_lstm_model.h5")
print("\n✅ Model saved at /mnt/data/tennis_shot_lstm_model.h5")

from google.colab import drive
drive.mount('/content/drive')

model.save("/content/drive/MyDrive/tennis_shot_lstm_model.h5")

!ls /content/drive/MyDrive

import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder


from tensorflow.keras.models import load_model

model = load_model("/content/drive/MyDrive/tennis_shot_lstm_model.h5")

print("Model loaded successfully!")





DATA_PATH = "/content/features_dataset_final (1).csv"

df = pd.read_csv(DATA_PATH)

print("Dataset shape:", df.shape)



feature_cols = [
    "wrist_vel","elbow_vel","ball_vel",
    "wrist_acc","ball_acc",
    "wrist_dx","wrist_dy","ball_dx","ball_dy",
    "arm_angle","arm_length",
    "wrist_ball_dist","elbow_ball_dist",
    "rel_speed","is_contact"
]



labels = [
    "forehand",
    "backhand",
    "serve",
    "volley"
]

le = LabelEncoder()
le.fit(labels)



SEQ_LEN = 20

X = []
index_map = []

for pid in df["player_id"].unique():

    sub = df[df["player_id"] == pid]

    for i in range(len(sub) - SEQ_LEN):

        seq = sub.iloc[i:i+SEQ_LEN][feature_cols].values

        X.append(seq)


        index_map.append(sub.index[i+SEQ_LEN])

X = np.array(X)

print("Prediction sequences:", X.shape)



pred = model.predict(X)

pred_labels = np.argmax(pred, axis=1)

shot_names = le.inverse_transform(pred_labels)



df["predicted_shot"] = "none"

for idx, shot in zip(index_map, shot_names):
    df.loc[idx, "predicted_shot"] = shot



OUTPUT = "/content/dataset_with_predictions.csv"

df.to_csv(OUTPUT, index=False)

print("Prediction completed")
print("Saved at:", OUTPUT)

print(df.head())