# -*- coding: utf-8 -*-
"""final_lstm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MnfzAlfWTOjbVOMpIakRk8r0mlSkJB7X
"""

# ================================================================
# LSTM TRAINING - Tennis Shot Classification (All 6 Classes)
# Forehand | Backhand | Serve | Smash | Volley | None
# ================================================================
#
# TO GET 85%+ ACCURACY WITH ALL 6 CLASSES YOU NEED:
#
#   Label ALL 5 videos: V006, V007, V008, V009, V010
#   using the labelling script (label_shots.py)
#
#   Why? Smash and Volley have only 3 events per video.
#   With 1-2 videos: ~80 Smash frames → model cannot learn.
#   With all 5 videos: ~400+ Smash frames → learnable.
#   This is a DATA problem, not a code problem.
#
# TECHNIQUES USED:
#   1. Majority-label windowing (70% purity) — removes boundary noise
#   2. Per-class equal balancing — no single class dominates
#   3. Gaussian noise augmentation (10x for rare, 3x for common)
#   4. Time-shift augmentation for Smash/Volley specifically
#   5. Pure-None windows only — removes noisy None sequences
#   6. Class weights — extra penalty for misclassifying rare shots
#   7. EarlyStopping on val_accuracy (not loss)
#   8. ReduceLROnPlateau for fine-tuning
#   9. BatchNormalization after every LSTM layer
#  10. GRU layer as final recurrent layer (faster + often better
#      than LSTM for short sequences)
# ================================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from collections import Counter

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.utils.class_weight import compute_class_weight
import seaborn as sns

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (Input, LSTM, GRU, Dense,
                                     Dropout, BatchNormalization,
                                     Bidirectional)
from tensorflow.keras.callbacks import (EarlyStopping, ReduceLROnPlateau,
                                        ModelCheckpoint)

from google.colab import drive
drive.mount('/content/drive')

# ================================================================
# 1. CONFIG
# ================================================================
DATASET_PATHS = [
    #"/content/drive/MyDrive/final_dataset_v006.csv",
    "/content/drive/MyDrive/final_dataset_v007.csv",
    "/content/drive/MyDrive/final_dataset_v008.csv",  # add as you label them
    #"/content/drive/MyDrive/final_dataset_v009.csv",
    "/content/drive/MyDrive/final_dataset_v010.csv",
]

SAVE_DIR   = "/content/drive/MyDrive/"
MODEL_NAME = "tennis_lstm_model_final.keras"

SEQ_LEN       = 20
PURITY_THRESH = 0.70   # window must be ≥70% the target class

# Augmentation multipliers per class
# Rare classes get more augmentation to compensate for fewer events
AUG_COMMON = 3    # Forehand, Backhand, Serve
AUG_RARE   = 15   # Smash, Volley  ← heavy augmentation for rare classes

NOISE_STD  = 0.05  # Gaussian noise std

FEATURE_COLS = [
    "wrist_vel", "elbow_vel", "ball_vel",
    "wrist_acc", "ball_acc",
    "wrist_dx",  "wrist_dy",
    "ball_dx",   "ball_dy",
    "arm_angle", "arm_length",
    "wrist_ball_dist", "elbow_ball_dist",
    "rel_speed", "is_contact"
]

# ================================================================
# 2. LOAD AND COMBINE DATASETS
# ================================================================
all_dfs = []

for path in DATASET_PATHS:
    try:
        df_temp = pd.read_csv(path)
    except FileNotFoundError:
        print(f"⚠️  Not found (skip): {path}")
        continue

    if "shot_type" not in df_temp.columns:
        print(f"⚠️  Skipping {path} — no shot_type column")
        continue

    # Fix: NaN and integer 0 → 'None'
    df_temp["shot_type"] = df_temp["shot_type"].fillna("None").astype(str)
    df_temp.loc[df_temp["shot_type"] == "0", "shot_type"] = "None"

    if df_temp["shot_type"].nunique() <= 1:
        print(f"⚠️  Skipping {path} — only one unique shot_type (unlabelled)")
        continue

    dist = df_temp["shot_type"].value_counts().to_dict()
    print(f"✅ Loaded {path} → {df_temp.shape}")
    print(f"   {dist}")
    all_dfs.append(df_temp)

if len(all_dfs) == 0:
    raise ValueError("No valid labelled datasets found.")

df = pd.concat(all_dfs, ignore_index=True)
print(f"\nCombined shape : {df.shape}")
print("\nFull shot distribution:")
print(df["shot_type"].value_counts())

# ================================================================
# 3. ENCODE LABELS  (all 6 classes kept)
# ================================================================
le = LabelEncoder()
df["label"] = le.fit_transform(df["shot_type"])
none_label = int(le.transform(["None"])[0])
n_classes  = len(le.classes_)
n_features = len(FEATURE_COLS)

print("\nLabel mapping:")
for cls, idx in zip(le.classes_, le.transform(le.classes_)):
    print(f"  {cls} → {idx}")

# Identify rare classes (Smash, Volley) for heavy augmentation
RARE_CLASSES = set()
for cls in ["Smash", "Volley"]:
    if cls in le.classes_:
        RARE_CLASSES.add(int(le.transform([cls])[0]))

np.save(SAVE_DIR + "label_classes.npy", le.classes_)
print(f"\n✅ Saved label_classes.npy  (classes: {list(le.classes_)})")

# ================================================================
# 4. BUILD SEQUENCES
# ================================================================
np.random.seed(42)

# Separate buckets per class
X_by_class = {i: [] for i in range(n_classes) if i != none_label}
X_none_pool = []

for pid in df["player_id"].unique():
    sub      = df[df["player_id"] == pid].reset_index(drop=True)
    features = sub[FEATURE_COLS].values
    labels   = sub["label"].values

    for i in range(len(sub) - SEQ_LEN):
        window   = labels[i : i + SEQ_LEN]
        cnt      = Counter(window)
        majority = cnt.most_common(1)[0][0]
        purity   = cnt[majority] / SEQ_LEN

        if majority == none_label:
            # Only pure-None windows (100%) with stride=15
            if i % 15 == 0 and purity == 1.0:
                X_none_pool.append(features[i : i + SEQ_LEN].astype(np.float32))
        else:
            if purity >= PURITY_THRESH:
                seq = features[i : i + SEQ_LEN].astype(np.float32)
                X_by_class[majority].append(seq)

# ================================================================
# 5. AUGMENTATION
# ================================================================
def augment_sequences(seqs, n_copies, noise_std=0.05):
    augmented = []
    for seq in seqs:
        for _ in range(n_copies):
            # Gaussian noise
            noisy = seq + np.random.normal(0, noise_std, seq.shape).astype(np.float32)
            augmented.append(noisy)
            # Time shift (shift by 1-3 frames, pad with zeros)
            if n_copies > 5:  # only for rare classes
                shift = np.random.randint(1, 4)
                shifted = np.zeros_like(seq)
                shifted[shift:] = seq[:-shift]
                augmented.append(shifted.astype(np.float32))
                # Scale variation (±10%)
                scale = np.random.uniform(0.9, 1.1)
                scaled = (seq * scale).astype(np.float32)
                augmented.append(scaled)
    return augmented

print("\nBuilding augmented sequences...")
X_augmented = {}
y_augmented = {}
total_shot_seqs = 0

for cls_idx, seqs in X_by_class.items():
    if len(seqs) == 0:
        print(f"  ⚠️  {le.classes_[cls_idx]}: 0 sequences — need more labelled data!")
        X_augmented[cls_idx] = []
        y_augmented[cls_idx] = []
        continue

    n_aug = AUG_RARE if cls_idx in RARE_CLASSES else AUG_COMMON
    aug   = augment_sequences(seqs, n_aug)
    all_seqs = seqs + aug

    print(f"  {le.classes_[cls_idx]}: {len(seqs)} raw → {len(all_seqs)} after aug ({n_aug}x)")
    X_augmented[cls_idx] = all_seqs
    y_augmented[cls_idx] = [cls_idx] * len(all_seqs)
    total_shot_seqs += len(all_seqs)

# None: cap at total shot sequences for equal balance
none_cap = total_shot_seqs
none_idx = np.random.choice(len(X_none_pool),
                             size=min(none_cap, len(X_none_pool)),
                             replace=False)
X_none_sel = [X_none_pool[i] for i in none_idx]
print(f"  None: {len(X_none_pool)} pool → {len(X_none_sel)} selected (cap={none_cap})")

# Combine all
X_all, y_all = [], []
for cls_idx in X_augmented:
    X_all.extend(X_augmented[cls_idx])
    y_all.extend(y_augmented[cls_idx])
X_all.extend(X_none_sel)
y_all.extend([none_label] * len(X_none_sel))

X = np.array(X_all, dtype=np.float32)
y = np.array(y_all, dtype=np.int32)

perm = np.random.permutation(len(X))
X, y = X[perm], y[perm]

print(f"\nFinal dataset   : {X.shape}")
print(f"Class balance   : {dict(Counter(y))}")
print(f"None ratio      : {Counter(y)[none_label]/len(y):.2%}")

# Check if Smash/Volley have enough data
for cls_name in ["Smash", "Volley"]:
    if cls_name in le.classes_:
        cls_idx = int(le.transform([cls_name])[0])
        count = Counter(y)[cls_idx]
        if count < 100:
            print(f"\n⚠️  WARNING: {cls_name} only has {count} sequences.")
            print(f"   The model will struggle with this class.")
            print(f"   Label more videos to get 85%+ accuracy on {cls_name}.")

# ================================================================
# 6. TRAIN / TEST SPLIT
# ================================================================
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)
print(f"\nTrain : {X_train.shape}")
print(f"Test  : {X_test.shape}")

# ================================================================
# 7. CLASS WEIGHTS
# ================================================================
class_weights = compute_class_weight(
    class_weight="balanced",
    classes=np.unique(y_train),
    y=y_train
)
class_weight_dict = dict(enumerate(class_weights))
print("\nClass weights:")
for idx, w in class_weight_dict.items():
    print(f"  {le.classes_[idx]} → {w:.3f}")

# ================================================================
# 8. MODEL
# Bidirectional LSTM: reads sequence forward AND backward
# → captures both the run-up and follow-through of a shot
# GRU final layer: faster than LSTM, handles short sequences well
# ================================================================
model = Sequential([
    Input(shape=(SEQ_LEN, n_features)),

    Bidirectional(LSTM(128, return_sequences=True)),
    BatchNormalization(),
    Dropout(0.3),

    Bidirectional(LSTM(64, return_sequences=True)),
    BatchNormalization(),
    Dropout(0.3),

    GRU(32),
    BatchNormalization(),
    Dropout(0.2),

    Dense(64, activation="relu"),
    Dropout(0.2),
    Dense(n_classes, activation="softmax")
])

model.compile(
    loss="sparse_categorical_crossentropy",
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    metrics=["accuracy"]
)

model.summary()

# ================================================================
# 9. TRAIN
# ================================================================
callbacks = [
    EarlyStopping(
        monitor="val_accuracy",
        patience=10,
        restore_best_weights=True,
        verbose=1
    ),
    ReduceLROnPlateau(
        monitor="val_loss",
        factor=0.5,
        patience=5,
        min_lr=1e-6,
        verbose=1
    ),
    ModelCheckpoint(
        filepath=SAVE_DIR + "best_" + MODEL_NAME,
        monitor="val_accuracy",
        save_best_only=True,
        verbose=1
    )
]

history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=30,
    batch_size=128,
    class_weight=class_weight_dict,
    callbacks=callbacks
)

# ================================================================
# 10. EVALUATE
# ================================================================
loss, acc = model.evaluate(X_test, y_test, verbose=0)
print(f"\n🎯 Test Accuracy : {acc:.4f}")
print(f"   Test Loss     : {loss:.4f}")

y_pred       = np.argmax(model.predict(X_test, batch_size=256), axis=1)
target_names = [str(c) for c in le.classes_]

print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=target_names))

plt.figure(figsize=(8, 6))
sns.heatmap(
    confusion_matrix(y_test, y_pred),
    annot=True, fmt="d",
    xticklabels=target_names,
    yticklabels=target_names,
    cmap="Blues"
)
plt.xlabel("Predicted"); plt.ylabel("True")
plt.title("Confusion Matrix - All 6 Classes")
plt.tight_layout()
plt.savefig(SAVE_DIR + "confusion_matrix.png")
plt.show()

plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(history.history["accuracy"],     label="Train")
plt.plot(history.history["val_accuracy"], label="Val")
plt.title("Accuracy"); plt.legend()
plt.subplot(1, 2, 2)
plt.plot(history.history["loss"],     label="Train")
plt.plot(history.history["val_loss"], label="Val")
plt.title("Loss"); plt.legend()
plt.tight_layout()
plt.savefig(SAVE_DIR + "training_curves.png")
plt.show()

# ================================================================
# 11. SAVE
# ================================================================
model.save(SAVE_DIR + MODEL_NAME)
print(f"\n✅ Model saved       : {SAVE_DIR + MODEL_NAME}")
print(f"✅ Best checkpoint   : {SAVE_DIR + 'best_' + MODEL_NAME}")
print(f"✅ label_classes.npy : {SAVE_DIR}label_classes.npy")
print(f"✅ Classes           : {target_names}")