# -*- coding: utf-8 -*-
"""final finding monemts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19FAdleUK0P909Hbsm8_DvY4SrkutX9rY
"""

import pandas as pd
import numpy as np


df = pd.read_csv("/content/V008_final_dataset.csv")

df = df.sort_values(["player_id", "frame_id"]).reset_index(drop=True)


df[["ball_x","ball_y"]] = df[["ball_x","ball_y"]].fillna(method="ffill").fillna(method="bfill")



def compute_angle(a, b, c):
    ba = a - b
    bc = c - b
    cosang = np.dot(ba, bc) / (np.linalg.norm(ba)*np.linalg.norm(bc) + 1e-6)
    return np.degrees(np.arccos(np.clip(cosang, -1, 1)))



for pid in df["player_id"].unique():

    idx = df["player_id"] == pid
    sub = df.loc[idx]
    prev = sub.shift(1)


    df.loc[idx, "wrist_vel"] = np.sqrt((sub["rw_x"]-prev["rw_x"])**2 + (sub["rw_y"]-prev["rw_y"])**2)
    df.loc[idx, "elbow_vel"] = np.sqrt((sub["re_x"]-prev["re_x"])**2 + (sub["re_y"]-prev["re_y"])**2)
    df.loc[idx, "ball_vel"]  = np.sqrt((sub["ball_x"]-prev["ball_x"])**2 + (sub["ball_y"]-prev["ball_y"])**2)


    df.loc[idx, "wrist_dx"] = sub["rw_x"] - prev["rw_x"]
    df.loc[idx, "wrist_dy"] = sub["rw_y"] - prev["rw_y"]
    df.loc[idx, "ball_dx"]  = sub["ball_x"] - prev["ball_x"]
    df.loc[idx, "ball_dy"]  = sub["ball_y"] - prev["ball_y"]



df["wrist_acc"] = df.groupby("player_id")["wrist_vel"].diff().fillna(0)
df["ball_acc"]  = df.groupby("player_id")["ball_vel"].diff().fillna(0)



arm_angles = []
wrist_dist = []
elbow_dist = []
arm_len = []

for i in range(len(df)):

    rs = np.array([df.loc[i,"rs_x"], df.loc[i,"rs_y"]])
    re = np.array([df.loc[i,"re_x"], df.loc[i,"re_y"]])
    rw = np.array([df.loc[i,"rw_x"], df.loc[i,"rw_y"]])

    bx, by = df.loc[i,["ball_x","ball_y"]]


    arm_angles.append(compute_angle(rs,re,rw))


    wrist_dist.append(np.sqrt((rw[0]-bx)**2 + (rw[1]-by)**2))
    elbow_dist.append(np.sqrt((re[0]-bx)**2 + (re[1]-by)**2))


    arm_len.append(np.sqrt((rs[0]-rw[0])**2 + (rs[1]-rw[1])**2))

df["arm_angle"] = arm_angles
df["wrist_ball_dist"] = wrist_dist
df["elbow_ball_dist"] = elbow_dist
df["arm_length"] = arm_len



df["rel_speed"] = df["ball_vel"] - df["wrist_vel"]


df["is_contact"] = (df["wrist_ball_dist"] < 80).astype(int)



df = df.fillna(0)



feature_cols = [
    "wrist_vel","elbow_vel","ball_vel",
    "wrist_acc","ball_acc",
    "wrist_dx","wrist_dy","ball_dx","ball_dy",
    "arm_angle","arm_length",
    "wrist_ball_dist","elbow_ball_dist",
    "rel_speed","is_contact"
]

for col in feature_cols:
    df[col] = (df[col] - df[col].mean()) / (df[col].std() + 1e-6)



OUT_PATH = "/content/V008_features_final.csv"
df.to_csv(OUT_PATH, index=False)

print("✅ FINAL FEATURE DATASET READY:", OUT_PATH)
print("Shape:", df.shape)
print(df.head())

import pandas as pd
import numpy as np


df = pd.read_csv("/content/final_dataset (3).csv")


df = df.rename(columns={"frame":"frame_id"})


df["rs_x"] = df["kp6_x"]
df["rs_y"] = df["kp6_y"]

df["re_x"] = df["kp8_x"]
df["re_y"] = df["kp8_y"]

df["rw_x"] = df["kp10_x"]
df["rw_y"] = df["kp10_y"]


df = df.sort_values(["player_id","frame_id"]).reset_index(drop=True)


df[["ball_x","ball_y"]] = df[["ball_x","ball_y"]].ffill().bfill()



def compute_angle(a,b,c):
    ba = a-b
    bc = c-b
    cosang = np.dot(ba,bc)/(np.linalg.norm(ba)*np.linalg.norm(bc)+1e-6)
    return np.degrees(np.arccos(np.clip(cosang,-1,1)))



df["wrist_vel"]=0
df["elbow_vel"]=0
df["ball_vel"]=0

df["wrist_dx"]=0
df["wrist_dy"]=0
df["ball_dx"]=0
df["ball_dy"]=0

for pid in df["player_id"].unique():

    mask = df["player_id"]==pid
    sub = df.loc[mask]
    prev = sub.shift(1)

    df.loc[mask,"wrist_vel"] = np.sqrt(
        (sub["rw_x"]-prev["rw_x"])**2 +
        (sub["rw_y"]-prev["rw_y"])**2
    )

    df.loc[mask,"elbow_vel"] = np.sqrt(
        (sub["re_x"]-prev["re_x"])**2 +
        (sub["re_y"]-prev["re_y"])**2
    )

    df.loc[mask,"ball_vel"] = np.sqrt(
        (sub["ball_x"]-prev["ball_x"])**2 +
        (sub["ball_y"]-prev["ball_y"])**2
    )

    df.loc[mask,"wrist_dx"] = sub["rw_x"]-prev["rw_x"]
    df.loc[mask,"wrist_dy"] = sub["rw_y"]-prev["rw_y"]

    df.loc[mask,"ball_dx"] = sub["ball_x"]-prev["ball_x"]
    df.loc[mask,"ball_dy"] = sub["ball_y"]-prev["ball_y"]



df["wrist_acc"] = df.groupby("player_id")["wrist_vel"].diff()
df["ball_acc"] = df.groupby("player_id")["ball_vel"].diff()



angles=[]
wrist_dist=[]
elbow_dist=[]
arm_len=[]

for _,row in df.iterrows():

    rs=np.array([row["rs_x"],row["rs_y"]])
    re=np.array([row["re_x"],row["re_y"]])
    rw=np.array([row["rw_x"],row["rw_y"]])

    bx=row["ball_x"]
    by=row["ball_y"]

    angles.append(compute_angle(rs,re,rw))

    wrist_dist.append(np.sqrt((rw[0]-bx)**2+(rw[1]-by)**2))
    elbow_dist.append(np.sqrt((re[0]-bx)**2+(re[1]-by)**2))

    arm_len.append(np.sqrt((rs[0]-rw[0])**2+(rs[1]-rw[1])**2))

df["arm_angle"]=angles
df["wrist_ball_dist"]=wrist_dist
df["elbow_ball_dist"]=elbow_dist
df["arm_length"]=arm_len



df["rel_speed"] = df["ball_vel"] - df["wrist_vel"]

df["is_contact"] = (df["wrist_ball_dist"] < 80).astype(int)



df = df.fillna(0)


feature_cols=[
"wrist_vel","elbow_vel","ball_vel",
"wrist_acc","ball_acc",
"wrist_dx","wrist_dy","ball_dx","ball_dy",
"arm_angle","arm_length",
"wrist_ball_dist","elbow_ball_dist",
"rel_speed","is_contact"
]

for col in feature_cols:
    df[col]=(df[col]-df[col].mean())/(df[col].std()+1e-6)



df["shot_type"] = 0



final_cols = [
'frame_id','player_id',
'rw_x','rs_x','re_x','rw_y','rs_y','re_y',
'ball_x','ball_y','shot_type',
'wrist_vel','elbow_vel','ball_vel',
'wrist_dx','wrist_dy','ball_dx','ball_dy',
'wrist_acc','ball_acc',
'arm_angle','wrist_ball_dist','elbow_ball_dist',
'arm_length','rel_speed','is_contact'
]

df = df[final_cols]



OUT_PATH="/content/features_dataset_final1.csv"

df.to_csv(OUT_PATH,index=False)

print("Features created successfully")
print("Dataset shape:",df.shape)
print(df.head())