# -*- coding: utf-8 -*-
"""mapping_shots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U-ciDt1Ug5KNEtU1-uuq6YK2VBZqmHzG
"""

# =========================================================
# FINAL CLEAN PIPELINE (FEATURES + TXT → LABELED DATASET)
# =========================================================

import pandas as pd
import numpy as np
from google.colab import drive

# ==========================================
# 1. MOUNT DRIVE
# ==========================================
drive.mount('/content/drive')

# ==========================================
# 2. PATHS (CHANGE IF NEEDED)
# ==========================================
FEATURE_PATH = "/content/drive/MyDrive/features_v010.csv"
TXT_PATH = "/content/drive/MyDrive/V010.txt"

# ==========================================
# 3. LOAD DATA
# ==========================================
df = pd.read_csv(FEATURE_PATH)
txt = pd.read_csv(TXT_PATH, sep=r"\s+", names=["frame", "label"])

print("Feature dataset:", df.shape)
print("TXT dataset:", txt.shape)

# ==========================================
# 4. BASIC CHECKS
# ==========================================
assert "frame_id" in df.columns, "❌ Missing frame_id"
assert "player_id" in df.columns, "❌ Missing player_id"
assert "wrist_ball_dist" in df.columns, "❌ Missing wrist_ball_dist"

# ==========================================
# 5. DECODE LABELS
# ==========================================
def decode(label):
    label = str(label)
    if label.startswith("HF"):
        return "Forehand"
    elif label.startswith("HN"):
        return "Backhand"
    elif label.startswith("SN"):
        return "Serve"
    elif label.startswith("V"):
        return "Volley"
    else:
        return None

txt["shot_type"] = txt["label"].apply(decode)

# remove invalid labels
txt = txt[txt["shot_type"].notna()]

print("\nDecoded label sample:")
print(txt.head())

# ==========================================
# 6. MERGE (CORRECT WAY)
# ==========================================
df = df.merge(
    txt[["frame", "shot_type"]],
    left_on="frame_id",
    right_on="frame",
    how="inner"
)

print("\nAfter merge:", df.shape)

# ==========================================
# 7. FIX COLUMN NAME (IMPORTANT)
# ==========================================
# sometimes pandas creates shot_type_x / shot_type_y
if "shot_type_y" in df.columns:
    df.rename(columns={"shot_type_y": "shot_type"}, inplace=True)

if "shot_type_x" in df.columns:
    df.drop(columns=["shot_type_x"], inplace=True)

# ==========================================
# 8. FIND HITTING PLAYER
# ==========================================
df["is_hitter"] = df.groupby("frame_id")["wrist_ball_dist"].transform(lambda x: x == x.min())

df = df[df["is_hitter"] == True].copy()

# ==========================================
# 9. REMOVE NOISE (CRITICAL)
# ==========================================
df = df[df["wrist_ball_dist"] < 100]

# ==========================================
# 10. CLEAN DATA
# ==========================================
df = df.drop(columns=["frame", "label", "is_hitter"], errors="ignore")

# ==========================================
# 11. FINAL CHECKS
# ==========================================
print("\nFinal dataset preview:")
print(df.head())

print("\nColumns:", df.columns.tolist())

if "shot_type" not in df.columns:
    raise ValueError("❌ shot_type still missing — stop here")

print("\nShot distribution:")
print(df["shot_type"].value_counts())

print("\nPlayers:", df["player_id"].unique())

# ==========================================
# 12. SAVE FINAL DATASET
# ==========================================
OUT_PATH = "/content/drive/MyDrive/final_labeled_dataset.csv"
df.to_csv(OUT_PATH, index=False)

print("\n✅ FINAL DATASET SAVED:", OUT_PATH)
print("Final shape:", df.shape)

# =========================================================
# FINAL VERSION (KEEP ALL ROWS + ADD NONE CLASS)
# =========================================================

import pandas as pd
import numpy as np
from google.colab import drive

# ==========================================
# 1. MOUNT DRIVE
# ==========================================
drive.mount('/content/drive')

# ==========================================
# 2. PATHS
# ==========================================
FEATURE_PATH = "/content/drive/MyDrive/features_v007.csv"
TXT_PATH = "/content/drive/MyDrive/V007.txt"

# ==========================================
# 3. LOAD DATA
# ==========================================
df = pd.read_csv(FEATURE_PATH)
txt = pd.read_csv(TXT_PATH, sep=r"\s+", names=["frame","label"])

print("Feature dataset:", df.shape)
print("TXT dataset:", txt.shape)

# ==========================================
# 4. DECODE LABELS
# ==========================================
def decode(label):
    label = str(label)
    if label.startswith("HF"):
        return "Forehand"
    elif label.startswith("HN"):
        return "Backhand"
    elif label.startswith("SN"):
        return "Serve"
    elif label.startswith("V"):
        return "Volley"
    elif label.startswith("SM"):
        return "Smash"
    else:
        return None

txt["shot_type"] = txt["label"].apply(decode)

# ==========================================
# 5. MERGE (KEEP ALL ROWS)
# ==========================================
df = df.merge(
    txt[["frame","shot_type"]],
    left_on="frame_id",
    right_on="frame",
    how="left"   # 🔥 IMPORTANT (no row loss)
)

print("\nAfter merge:", df.shape)

# ==========================================
# 6. FIX COLUMN NAME
# ==========================================
if "shot_type_y" in df.columns:
    df.rename(columns={"shot_type_y": "shot_type"}, inplace=True)

df.drop(columns=["shot_type_x"], errors="ignore", inplace=True)

# ==========================================
# 7. ASSIGN NONE CLASS
# ==========================================
df["shot_type"] = df["shot_type"].fillna("None")

# ==========================================
# 8. FINAL CLEANUP
# ==========================================
df = df.drop(columns=["frame","label"], errors="ignore")

# ==========================================
# 9. CHECK OUTPUT
# ==========================================
print("\nFinal dataset preview:")
print(df.head())

print("\nFinal shape (should be SAME as original):", df.shape)

print("\nShot distribution:")
print(df["shot_type"].value_counts())

print("\nClasses:", df["shot_type"].unique())

# ==========================================
# 10. SAVE
# ==========================================
OUT_PATH = "/content/drive/MyDrive/final_dataset_v007.csv"
df.to_csv(OUT_PATH, index=False)

print("\n✅ FINAL DATASET SAVED:", OUT_PATH)

import pandas as pd
import numpy as np
import json
from google.colab import drive

drive.mount('/content/drive')

# ==========================================
# 1. PATHS
# ==========================================
FEATURE_PATH = "/content/drive/MyDrive/features_v008.csv"
JSON_PATH    = "/content/drive/MyDrive/V008.json"

# ==========================================
# 2. LOAD DATA
# ==========================================
df = pd.read_csv(FEATURE_PATH)
with open(JSON_PATH) as f:
    data = json.load(f)

print("Feature dataset:", df.shape)

# ==========================================
# 3. AUTO-DETECT PLAYER_ID → NAME PER SET
# Logic: player_id is position-based (tracking ID)
#        1 = bottom of frame (higher y = Near)
#        2 = top of frame (lower y = Far)
#        Near/Far player NAME switches each set
#        So we detect per set using avg y position
# ==========================================
all_players = list(set([g['custom']['Winner'] for g in data['classes']['Game']]))
print("Players in match:", all_players)

set_player_map = {}  # set_name → {player_id: player_name, start, end}

for s in data['classes']['Set']:
    s_start   = int(s['start'])
    s_end     = int(s['end'])
    near_name = s['custom']['Near']
    far_name  = [p for p in all_players if p != near_name][0]

    sub   = df[(df['frame_id'] >= s_start) & (df['frame_id'] <= s_end)]
    avg_y = sub.groupby('player_id')['rs_y'].mean()

    near_pid = avg_y.idxmax()  # higher y = Near (bottom of frame)
    far_pid  = avg_y.idxmin()  # lower y  = Far (top of frame)

    set_player_map[s['name']] = {
        'start':   s_start,
        'end':     s_end,
        near_pid:  near_name,
        far_pid:   far_name
    }
    print(f"  Set {s['name']}: {near_name}=pid{near_pid}(Near), {far_name}=pid{far_pid}(Far)")

def get_player_name(frame_id, player_id):
    for sinfo in set_player_map.values():
        if sinfo['start'] <= frame_id <= sinfo['end']:
            return sinfo.get(player_id, None)
    return None

# ==========================================
# 4. BUILD LABEL MAP: (frame, player_name) → shot
# ==========================================
label_map = {}

# Hits
for hit in data['classes']['Hit']:
    start  = int(hit['start'])
    end    = int(hit['end'])
    player = hit['custom']['Player']
    htype  = hit['custom'].get('Type', '')
    side   = hit['custom'].get('Side', '')

    if htype == 'Smash':
        label = 'Smash'
    elif htype == 'Volley':
        label = 'Volley'
    elif side == 'Forehand':
        label = 'Forehand'
    elif side == 'Backhand':
        label = 'Backhand'
    else:
        label = 'None'

    for frame in range(start, end):
        label_map[(frame, player)] = label

# Serves
for serve in data['classes']['Serve']:
    start  = int(serve['start'])
    end    = int(serve['end'])
    player = serve['custom']['Player']
    for frame in range(start, end):
        label_map[(frame, player)] = 'Serve'

# ==========================================
# 5. APPLY LABELS (frame + player_id matched)
# ==========================================
def get_label(row):
    pname = get_player_name(row['frame_id'], row['player_id'])
    if pname is None:
        return 'None'
    return label_map.get((row['frame_id'], pname), 'None')

df['shot_type'] = df.apply(get_label, axis=1)

# ==========================================
# 6. CHECK
# ==========================================
print("\nFinal shape:", df.shape)
print("\nOverall shot distribution:")
print(df['shot_type'].value_counts())

print("\nPer player_id breakdown:")
for pid in df['player_id'].unique():
    frames_in_sets = sum(
        1 for sinfo in set_player_map.values()
        if sinfo.get(pid)
    )
    sub = df[df['player_id'] == pid]
    # find name from any set
    sample_frame = sub['frame_id'].iloc[0]
    name = get_player_name(sample_frame, pid) or f"player_id={pid}"
    print(f"\n  {name} (player_id={pid}):")
    print(sub['shot_type'].value_counts().to_string())

# ==========================================
# 7. SAVE
# ==========================================
OUT_PATH = "/content/drive/MyDrive/final_dataset_v010.csv"
df.to_csv(OUT_PATH, index=False)
print("\n✅ Saved:", OUT_PATH)