# -*- coding: utf-8 -*-
"""pedicting_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AzAUs1ERM0gpy4epmL31ZGjtlzuiaHyp
"""

# ================================================================
# LSTM PREDICTION - Tennis Shot Classification
# ================================================================
# Input : any features CSV (same columns as training data)
# Output: same CSV with two new columns added:
#           predicted_shot  → Forehand / Backhand / Serve /
#                             Smash / Volley / None
#           confidence      → 0.0 to 1.0
#
# All original columns kept exactly as they are.
# Rows in the first SEQ_LEN frames of each player get
# predicted_shot='None' and confidence=0.0 (no full window yet).
# ================================================================

import pandas as pd
import numpy as np
from tensorflow.keras.models import load_model

from google.colab import drive
drive.mount('/content/drive')

# ================================================================
# 1. CONFIG  ← only change these paths
# ================================================================
MODEL_PATH   = "/content/drive/MyDrive/tennis_lstm_model.keras"
CLASSES_PATH = "/content/drive/MyDrive/label_classes.npy"
INPUT_PATH   = "/content/drive/MyDrive/features_v010.csv"   # your input
OUTPUT_PATH  = "/content/drive/MyDrive/predictions_v010.csv"

SEQ_LEN = 20   # must match training

FEATURE_COLS = [
    "wrist_vel", "elbow_vel", "ball_vel",
    "wrist_acc", "ball_acc",
    "wrist_dx",  "wrist_dy",
    "ball_dx",   "ball_dy",
    "arm_angle", "arm_length",
    "wrist_ball_dist", "elbow_ball_dist",
    "rel_speed", "is_contact"
]

# ================================================================
# 2. LOAD MODEL + CLASSES
# ================================================================
model   = load_model(MODEL_PATH)
classes = np.load(CLASSES_PATH, allow_pickle=True)

print("✅ Model loaded")
print(f"✅ Classes : {list(classes)}")
model.summary()

# ================================================================
# 3. LOAD INPUT FILE
# ================================================================
df = pd.read_csv(INPUT_PATH)
print(f"\nInput shape : {df.shape}")
print(f"Columns     : {df.columns.tolist()}")

# Validate all required feature columns are present
missing = [c for c in FEATURE_COLS if c not in df.columns]
if missing:
    raise ValueError(f"Missing columns in input file: {missing}")

# ================================================================
# 4. INITIALISE OUTPUT COLUMNS
# ================================================================
df["predicted_shot"] = "None"
df["confidence"]     = 0.0

# ================================================================
# 5. PREDICT PER PLAYER
# ================================================================
for pid in sorted(df["player_id"].unique()):

    # Keep original index so we can write predictions back correctly
    sub      = df[df["player_id"] == pid].copy()
    orig_idx = sub.index.values          # original row positions in df
    features = sub[FEATURE_COLS].values  # shape: (n_rows, 15)

    if len(sub) <= SEQ_LEN:
        print(f"⚠️  player_id={pid} — only {len(sub)} rows, need >{SEQ_LEN}, skipping")
        continue

    n_seqs = len(sub) - SEQ_LEN

    # Build all sequences for this player at once
    X = np.stack(
        [features[i : i + SEQ_LEN] for i in range(n_seqs)],
        axis=0
    ).astype(np.float32)   # shape: (n_seqs, SEQ_LEN, 15)

    # Predict
    probs      = model.predict(X, batch_size=256, verbose=0)  # (n_seqs, n_classes)
    pred_ids   = np.argmax(probs, axis=1)                      # (n_seqs,)
    pred_names = classes[pred_ids]                             # (n_seqs,)
    confidence = np.max(probs, axis=1)                        # (n_seqs,)

    # Each prediction at position i corresponds to orig_idx[i + SEQ_LEN]
    target_indices = orig_idx[SEQ_LEN : SEQ_LEN + n_seqs]

    df.loc[target_indices, "predicted_shot"] = pred_names
    df.loc[target_indices, "confidence"]     = np.round(confidence, 4)

    print(f"player_id={pid} : {n_seqs} sequences predicted")

# ================================================================
# 6. SUMMARY
# ================================================================
print("\n── Predicted shot distribution ──")
print(df["predicted_shot"].value_counts())

predicted = df[df["predicted_shot"] != "None"]
if len(predicted) > 0:
    print("\n── Average confidence per shot ──")
    print(predicted.groupby("predicted_shot")["confidence"].mean().round(3))

print(f"\nTotal rows        : {len(df)}")
print(f"Rows with prediction : {(df['predicted_shot'] != 'None').sum()}")
print(f"Rows without (first {SEQ_LEN} per player) : {(df['predicted_shot'] == 'None').sum()}")

# ================================================================
# 7. SAVE
# ================================================================
df.to_csv(OUTPUT_PATH, index=False)
print(f"\n✅ Saved  : {OUTPUT_PATH}")
print(f"   Shape  : {df.shape}")
print(f"   Columns: {df.columns.tolist()}")